"""empty message

Revision ID: 332f934572e9
Revises: 
Create Date: 2025-11-15 21:56:26.132757

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '332f934572e9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorie',
    sa.Column('id_categorie', sa.Integer(), nullable=False),
    sa.Column('nom_categorie', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id_categorie'),
    sa.UniqueConstraint('nom_categorie')
    )
    op.create_table('vendeur',
    sa.Column('id_vendeur', sa.Integer(), nullable=False),
    sa.Column('nom', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id_vendeur'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('nom')
    )
    with op.batch_alter_table('vendeur', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vendeur_created_at'), ['created_at'], unique=False)

    op.create_table('boutique',
    sa.Column('id_boutique', sa.Integer(), nullable=False),
    sa.Column('id_vendeur', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('domaine', sa.String(length=150), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_vendeur'], ['vendeur.id_vendeur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_boutique'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('name')
    )
    with op.batch_alter_table('boutique', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_boutique_created_at'), ['created_at'], unique=False)

    op.create_table('produit',
    sa.Column('id_product', sa.Integer(), nullable=False),
    sa.Column('id_vendeur', sa.Integer(), nullable=False),
    sa.Column('id_category', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('image', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_category'], ['categorie.id_categorie'], ),
    sa.ForeignKeyConstraint(['id_vendeur'], ['vendeur.id_vendeur'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id_product')
    )
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_produit_updated_at'), ['updated_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produit', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_produit_updated_at'))

    op.drop_table('produit')
    with op.batch_alter_table('boutique', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_boutique_created_at'))

    op.drop_table('boutique')
    with op.batch_alter_table('vendeur', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vendeur_created_at'))

    op.drop_table('vendeur')
    op.drop_table('categorie')
    # ### end Alembic commands ###
